apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ${SERVICE}
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      serviceAccountName: ${SA}
      containers:
      - image: ${IMAGE}
  traffic:
  - percent: 100
    latestRevision: true
